name: Build ISOs
on:
  push:
    tags:
      - "*.*.*"

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_name:
          [hyprland-nvidia]
        fedora_version: [40]
    env:
      IMAGE_TAG: latest
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Build ISOs
        uses: jasonn3/build-container-installer@v1.2.2
        id: build
        with:
          iso_name: ${{ matrix.image_name }}-${{ github.ref_name }}.iso
          arch: x86_64
          image_name: ${{ matrix.image_name }}
          image_repo: ${{ steps.registry_case.outputs.lowercase }}
          # We cannot use Silverblue variant since we need the user creation options in anaconda
          variant: "Kinoite"
          version: ${{ matrix.fedora_version }}
          image_tag: ${{ env.IMAGE_TAG }}
          secure_boot_key_url: "https://github.com/ublue-os/akmods/raw/main/certs/public_key.der"
          enrollment_password: "celestial"
          flatpak_remote_refs_dir: ${{ steps.flatpak-dependencies.outputs.FLATPAK_REFS_DIR }}
          enable_flatpak_dependencies: false

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
            LICENSE